services:
  frontend:
    image: ghcr.io/talodev/frontend:latest
    environment:
      - API_URL=https://${BACKEND_DOMAIN}

  backend:
    image: ghcr.io/talodev/backend:latest
    restart: on-failure
    volumes:
      - .env:/usr/backend/.env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.4
    command: --mysql-native-password=ON
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    
  redis:
    image: bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  web:
    image: caddy:2.8-alpine
    restart: unless-stopped
    environment:
      - FRONTEND_DOMAIN=${FRONTEND_DOMAIN}
      - BACKEND_DOMAIN=${BACKEND_DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./config/Caddyfile:/etc/caddy/Caddyfile
    depends_on:
      - frontend
      - backend

volumes:
  db_data:
  caddy_data:
  caddy_config:
