version: '3.9'

services:
  backend:
    image: ghcr.io/talodev/backend:latest
    ports:
      - ${PROXY_PORT}:9000
    volumes:
      - ./.env:/usr/backend/.env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    
  redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379

  web:
    image: jonasal/nginx-certbot:2.4.0-alpine
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=${CA_EMAIL}
      - PROXY_PORT=${PROXY_PORT}
      - DOMAIN_NAME=${CA_DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - certs:/etc/letsencrypt
      - ./config/nginx:/etc/nginx/templates
    depends_on:
      - backend

volumes:
  data:
  certs:
