version: '3.8'

services:
  backend:
    image: ghcr.io/talodev/backend:latest
    restart: on-failure
    volumes:
      - .env:/usr/backend/.env
    depends_on:
      - db
      - redis

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password --sql_mode=
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    restart: always
    ports:
      - 3306:3306
    volumes:
      - data:/var/lib/mysql
    
  redis:
    image: bitnami/redis:6.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379

  web:
    image: nginx:latest
    restart: unless-stopped
    volumes:
      - ./config/nginx:/etc/nginx/templates
    ports:
      - ${PROXY_PORT}:80
    depends_on:
      - backend

volumes:
  data:
