services:
  frontend:
    image: ghcr.io/talodev/frontend:latest
    environment:
      - API_URL=http://localhost:${BACKEND_PORT}
    ports:
      - 80:80

  backend:
    image: ghcr.io/talodev/backend:latest
    restart: on-failure
    volumes:
      - .env:/usr/backend/.env
    ports:
      - ${BACKEND_PORT}:80
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.4
    command: --mysql-native-password=ON
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    
  redis:
    image: bitnami/redis:7.2
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  clickhouse:
    image: ghcr.io/talodev/clickhouse:latest
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    restart: unless-stopped
    ports:
      - ${CLICKHOUSE_PORT}:8123
    volumes:
      - clickhouse-data:/var/lib/clickhouse

volumes:
  db-data:
  clickhouse-data:
